name: Build DLL

on: workflow_dispatch

jobs:
  build_x64:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSVC x64
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '16.0'
          msbuild-architecture: x64

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14.1
        with:
          cmake-version: '3.24'

      - name: Configure CMake x64 Release
        run: cmake -B build_mc_win10_crack_x64 -G "Visual Studio 17" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build x64 Release
        run: cmake --build build_mc_win10_crack_x64 --config Release

      - name: Move files to root Release
        run: |
          mv build_mc_win10_crack_x64/Release/mc_win10_crack.dll .

      - name: Upload x64 artifacts Release
        uses: actions/upload-artifact@v2
        with:
          name: x64_Release
          path: |
            mc_win10_crack.dll